/*
   This file was generated automatically by the Mojo IDE version B1.3.3.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    output reg [7:0] io_led,
    input [2:0] io_dip,
    input carry,
    input sum,
    output reg a,
    output reg b,
    output reg c
  );
  
  
  
  reg rst;
  
  reg [3:0] result;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = 8'h00;
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    io_led[0+7-:8] = 8'h00;
    io_led[0+0-:1] = io_dip[0+0-:1];
    io_led[1+0-:1] = io_dip[1+0-:1];
    io_led[2+0-:1] = io_dip[2+0-:1];
    io_led[3+0-:1] = sum;
    io_led[4+0-:1] = carry;
    a = io_dip[0+0-:1];
    b = io_dip[1+0-:1];
    c = io_dip[2+0-:1];
    result = io_dip[0+0-:1] + io_dip[1+0-:1] + io_dip[2+0-:1];
    if (result == 2'h3) begin
      io_led[7+0-:1] = 1'h1;
      io_led[6+0-:1] = 1'h1;
    end else begin
      if (result == 2'h2) begin
        io_led[7+0-:1] = 1'h1;
        io_led[6+0-:1] = 1'h0;
      end else begin
        if (result == 1'h1) begin
          io_led[7+0-:1] = 1'h0;
          io_led[6+0-:1] = 1'h1;
        end else begin
          io_led[7+0-:1] = 1'h0;
          io_led[6+0-:1] = 1'h0;
        end
      end
    end
  end
endmodule
